# Generated by Django 4.1.3 on 2024-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billmanager',
            options={'verbose_name': 'Соотношения счет'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('canceled', 'Отменено'), ('success', 'Успешна')], default='pending', max_length=16),
        ),
    ]
